#!/usr/bin/perl -w

use strict;
use Cwd 'cwd';

my $home=$ENV{HOME};
my $homeBinDir="$home/bin";
my $cwd = cwd();

sub runCommand($) {
    my ($command) = @_;
    open CMD, "$command |" || die "Unable to run $command: $!";
    my @output = <CMD>;
    close CMD;
    return @output;
}

MAIN: {
    print "Updating dotfiles...\n";
    opendir(DH, "$cwd/.files");
    my @files = readdir(DH);
    closedir(DH);
    foreach (@files) {
        # skip . and ..
        next if($_ =~ /^\.$/);
        next if($_ =~ /^\.\.$/);

        print join('', runCommand("ln -sfv $cwd/.files/$_ $home"));
    }
    print join('', runCommand("ln -sfv $cwd/.config/nvim $home/.config"));

    `mkdir -p $homeBinDir`;
    `mkdir -p $homeBinDir/save`;
    `cp bin/bin/* $homeBinDir`;

    my $dictionaryDir="$home/dictionary";
    print "\nupdating dictionary...\n";
    if (!-d "$dictionaryDir") {
        `git clone git\@github.com:jonbri/dictionary.git $dictionaryDir`;
    } else {
        `git -C $dictionaryDir fetch`;
    }

    my $marbleDir="$home/marble";
    print "\nupdating marble...\n";
    if (!-d "$marbleDir") {
        `git clone git\@github.com:jonbri/marble.git $marbleDir`;
    } else {
        `git -C $marbleDir fetch`;
    }

    print "\nDone\n";
    print join('', runCommand("welcome --quiet"));
}

