#!/usr/bin/perl -w

use strict;
use Cwd 'cwd';

my $home=$ENV{HOME};
my $cwd = cwd();

my @repos=qw(
    https://github.com/jonbri/killer|killer
    https://github.com/jonbri/persona|persona
);

sub runCommand($) {
    my ($command) = @_;
    open CMD, "$command |" || die "Unable to run $command: $!";
    my @output = <CMD>;
    close CMD;
    return @output;
}

sub welcome() {
    print join('', runCommand("welcome"));
}

MAIN: {
    print "Updating dotfiles...\n";
    opendir(DH, "$cwd/.files");
    my @files = readdir(DH);
    closedir(DH);
    foreach (@files) {
        # skip . and ..
        next if($_ =~ /^\.$/);
        next if($_ =~ /^\.\.$/);

        print join('', runCommand("ln -sfv $cwd/.files/$_ $home"));
    }
    print join('', runCommand("ln -sfv $cwd/.config/nvim $home/.config"));

    print "\nUpdating tools...\n";

    my $toolsDir="$home/tools";
    my $homeBinDir="$home/bin";

    `mkdir -p $toolsDir`;
    `mkdir -p $homeBinDir`;
    `cp bin/bin/* $homeBinDir`;

    my ($repo,$folderName);
    foreach(@repos) {
        ($repo,$folderName)=split("\Q|",$_,2);

        my $fullPath="$toolsDir/$folderName";
        my $main = `cd $fullPath && main`;
        if (-d "$fullPath") {
            `git -C $fullPath stash -u`;
            `git -C $fullPath fetch`;
            `git -C $fullPath checkout $main`;
            `git -C $fullPath reset --hard origin/$main`;
        } else {
            `git clone $repo $fullPath --depth 1`;
        }
    }

    my $dictionaryDir="$home/dictionary";
    if (!-d "$dictionaryDir") {
        `git clone git\@github.com:jonbri/dictionary.git $dictionaryDir`;
    } else {
        `git -C $dictionaryDir fetch`;
    }

    my $marbleDir="$home/marble";
    if (!-d "$marbleDir") {
        `git clone git\@github.com:jonbri/marble.git $marbleDir`;
    } else {
        `git -C $marbleDir fetch`;
    }

    print "\nDone\n";
    welcome();
}

