#!/bin/bash

ZARGS_LOC=$HOME/.vim/bundle/jonbri-zargs/zargs

mkdir -p $ZARGS_LOC

find $NC/src/nova-commons/src/components/ObjectManager -type f > $ZARGS_LOC/objectmgr

cat << EOF > $ZARGS_LOC/packagejson
${NC}/src/nova-commons/package.json
${NC}/src/nova-commons-i18n-gen/package.json
${NC}/src/nova-commons-assets/package.json
${NC}/src/nova-core/package.json
${NC}/package.json
${NC}/scripts/package.json
${NC}/apps/showcase/ui/package.json
${NC}/build/nova-commons/package.json
${NC}/build/nova-commons-i18n-gen/package.json
${NC}/build/nova-core/package.json
${NC}/tools/templates/base/package.json
${NC}/tools/create-nova-app/package.json
${NC}/tools/nova-scripts/package.json
${NC}/tools/create-nova-app/createNovaApp.js
EOF

cat << EOF > $ZARGS_LOC/ui5honeycomb
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/honeycomb.json
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/library.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/Application.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/SamplesModel.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/controlViewer/ControlViewer.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/util/InteractiveSampleBase.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/util/SampleLoader.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/util/samplesUtil.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/util/targetExampleUtil.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/HomeDetailView.view.xml
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/Honeycomb.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/HoneycombMin.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/SnippetView.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/TreeNavigation.view.xml
/home/jonbri/ui5/openui-honeycomb-themes/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/themes/sas_base/library.less
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/test/sas/honeycomb/SamplesModel.qunit.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/messagebundle.properties
EOF

cat << EOF > $ZARGS_LOC/ui5honeycomb-all
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/honeycomb.json
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/library.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/ASMApp.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/ASMApp.controller.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/AppSwitcherModel.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/Application.controller.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/Application.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/SamplesModel.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/SSEApp.controller.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/SSEApp.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/controlViewer/ControlViewer.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/controlViewer/ControlViewerRenderer.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/controlViewer/Example.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/controlViewer/ExampleRenderer.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/controlViewer/Section.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/controlViewer/ViewExample.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/util/InteractiveSampleBase.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/util/SnippetNameValidationAdapter.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/util/SampleLoader.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/util/samplesUtil.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/util/targetExampleUtil.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/HomeDetailView.controller.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/HomeDetailView.view.xml
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/Honeycomb.controller.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/Honeycomb.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/HoneycombMin.controller.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/HoneycombMin.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/SnippetView.controller.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/SnippetView.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/TreeNavigation.view.xml
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/TreeNavigation.controller.js
/home/jonbri/ui5/openui-honeycomb-themes/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/themes/sas_base/library.less
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/test/sas/honeycomb/SamplesModel.qunit.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/messagebundle.properties
EOF

cat << EOF > $ZARGS_LOC/ui5lifecycle
/home/jonbri/ui5/openui-sdk/src/sap.ui.core/src/sap/ui/core/Control.js
/home/jonbri/ui5/openui-sdk/src/sap.ui.core/src/sap/ui/core/Element.js
/home/jonbri/ui5/openui-sdk/src/sap.ui.core/src/sap/ui/base/ManagedObject.js
/home/jonbri/ui5/openui-sdk/src/sap.ui.core/src/sap/ui/base/EventProvider.js
/home/jonbri/ui5/openui-sdk/src/sap.ui.core/src/sap/ui/base/Object.js
EOF

cat << EOF > $ZARGS_LOC/ui5masonry
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.layout/src/sas/hc/ui/layout/Masonry.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.layout/src/sas/hc/ui/layout/MasonryData.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.layout/src/sas/hc/ui/layout/MasonryLayoutMode.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.layout/src/sas/hc/ui/layout/MasonryTile.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.layout/test/sas/hc/ui/layout/qunit/Masonry.qunit.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/Masonry.view.js
EOF

cat << EOF > $ZARGS_LOC/ui5messagedialog
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/MessageDialog.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/test/sas/hc/m/qunit/MessageDialog.qunit.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/MessageDialog.view.js
EOF

cat << EOF > $ZARGS_LOC/ui5messagesummary
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/MessageSummary.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/test/sas/hc/m/qunit/MessageSummary.qunit.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/MessageSummary.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/_MessageSummaryInteractiveSample.js
EOF

cat << EOF > $ZARGS_LOC/ui5objectinspector
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/objectInspector/ObjectInspector.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/objectInspector/ObjectInspectorBase.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/objectInspector/FormatUtil.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/objectInspector/_FavoritesButton.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/objectInspector/_GenericContainer.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/objectInspector/_IconTabBar.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/objectInspector/_ObjectInspectorNamedButton.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/objectInspector/_ObjectInspectorPopoverContainer.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/test/sas/hc/m/objectInspector/qunit/ObjectInspector.qunit.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectInspector.view.js
/home/jonbri/ui5/openui-framework-themes/src/main/openuilibs/sas.hc.m/src/sas/hc/m/themes/sas_base/objectInspector.less
/home/jonbri/ui5/openui-framework-themes/src/main/openuilibs/sas.hc.m/src/sas/hc/m/themes/sas_corporate/objectInspector_corporate.less
/home/jonbri/ui5/openui-framework-themes/src/main/openuilibs/sas.hc.ui.core/src/sas/hc/ui/core/themes/sas_hcb/hc_variables/objectInspector_hc_variables.less
/home/jonbri/ui5/openui-framework-themes/src/main/openuilibs/sas.hc.ui.core/src/sas/hc/ui/core/themes/sas_ignite/variables/objectInspector_ignite_variables.less
/home/jonbri/ui5/openui-framework-themes/src/main/openuilibs/sas.hc.ui.core/src/sas/hc/ui/core/themes/sas_base/variables/objectInspector_variables.less
/home/jonbri/ui5/openui-framework-themes/src/main/openuilibs/sas.hc.ui.core/src/sas/hc/ui/core/themes/sas_corporate/corporate_variables/objectInspector_corporate_variables.less
EOF

cat << EOF > $ZARGS_LOC/ui5objectmanager
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/BaseObjectManagerView.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/BaseObjectNavigatorPage.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ButtonGroup.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/CustomBar.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/CustomIconTabBar.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/HeaderDivider.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/HeaderGroup.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ListObjectManagerView.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/MasonryObjectManagerView.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectContentPage.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectDialog.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectManager.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectManagerMasonry.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectManagerMasonryTile.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectManagerMasonryTileRenderer.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectManagerPage.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectManagerTile.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectManagerTileMasonry.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectManagerUtil.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectManagerViewRenderer.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ObjectNavigator.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/TableObjectManagerView.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/TileObjectManagerView.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.objectmgr/src/sas/hc/ui/objectmgr/ValidationHelper.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectManager.controller.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectManager.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectManagerAnotherPage.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectManagerDialogFirstPage.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectManagerDrillInDetails.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectManagerDrillInPage.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectManagerDrillInPage.controller.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectManagerPage.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectManagerPage.controller.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectManagerTargetPage.controller.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectManagerTargetPage.view.js
EOF

cat << EOF > $ZARGS_LOC/ui5pageablelayout
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/PageableLayout.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/test/sas/hc/m/qunit/PageableLayout.qunit.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/test/sas/hc/m/qunit/PageableLayout_static.qunit.js
/home/jonbri/ui5/openui-framework-themes/src/main/openuilibs/sas.hc.m/src/sas/hc/m/themes/sas_base/pageableLayout.less
/home/jonbri/ui5/openui-framework-themes/src/main/openuilibs/sas.hc.m/src/sas/hc/m/themes/sas_corporate/pageableLayout_corporate.less
/home/jonbri/ui5/openui-framework-themes/src/main/openuilibs/sas.hc.ui.core/src/sas/hc/ui/core/themes/sas_base/variables/pageableLayout_variables.less
/home/jonbri/ui5/openui-framework-themes/src/main/openuilibs/sas.hc.ui.core/src/sas/hc/ui/core/themes/sas_corporate/corporate_variables/pageableLayout_corporate_variables.less
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/PageableLayout.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/_PageableLayoutInteractiveSample.js
EOF

cat << EOF > $ZARGS_LOC/ui5simplepairtable
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/SimplePairTable.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/test/sas/hc/m/qunit/SimplePairTable.qunit.js
EOF

cat << EOF > $ZARGS_LOC/ui5table
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/Table.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/CheckBox.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/Column.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/ColumnDragBar.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/ColumnDragBarHandleIcon.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/ColumnMenu.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/ColumnMenuRenderer.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/DraggableRowDelegate.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/DroppableTableDelegate.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/ItemNavigation.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/Row.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/SelectAllControl.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/Table.designtime.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TableAccExtension.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TableAccRenderExtension.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TableExtension.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TableGrouping.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TableKeyboardDelegate.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TableKeyboardExtension.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TableOptionsColumnsDialog.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TableOptionsMenuButton.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TablePointerExtension.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TableRenderer.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TableUtils.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TreeSelectionModel.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TreeTable.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TreeTableRenderer.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TriStateCheckBox.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/TriStateSelectAll.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/WideRow.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/WideTable.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/WideTableRenderer.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/src/sas/hc/ui/table/WideTreeTable.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.core/src/sas/hc/ui/core/delegate/TableClickHandlerDelegate.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.ui.table/test/sas/hc/ui/table/qunit/Table.qunit.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/TableBumbleFly1.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/TableBumbleFly2.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/TableBumbleFly3.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/TableBumbleFly4.view.js
/home/jonbri/ui5/openui-sdk/src/sap.ui.core/src/sap/ui/model/SelectionModel.js
/home/jonbri/ui5/openui-sdk/src/sap.ui.core/src/sap/ui/core/delegate/ItemNavigation.js
EOF

cat << EOF > $ZARGS_LOC/ui5tile
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/TileBase.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/ObjectTile.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/ContainerTile.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/PresentationTile.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/test/sas/hc/m/qunit/TileBase.qunit.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/test/sas/hc/m/qunit/ObjectTile.qunit.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/test/sas/hc/m/qunit/ContainerTile.qunit.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/test/sas/hc/m/qunit/PresentationTile.qunit.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ObjectTile.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/ContainerTile.view.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/controls/PresentationTile.view.js
EOF

cat << EOF > $ZARGS_LOC/ui5welcome
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeExperience.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeAnimationTimer.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeAvatar.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeCarouselDots.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeEvent.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeHBox.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeIntro.controller.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeIntro.view.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeOutro.controller.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeOutro.view.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeProfile.controller.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeProfile.view.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeThemesCarousel.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeThemes.controller.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeThemes.view.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeThemeTile.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/welcome/WelcomeVBox.js
/home/jonbri/ui5/openui-honeycomb/src/main/openuilibs/sas.honeycomb/src/sas/honeycomb/views/Honeycomb.controller.js
/home/jonbri/ui5/openui-framework/src/main/openuilibs/sas.hc.m/src/sas/hc/m/messagebundle.properties
EOF

echo "zargs updated"

