#!/bin/bash

ZARGS_LOC=$HOME/.config/zargs

mkdir -p $ZARGS_LOC

# dotfiles
find $DOTFILES_DIR -type f -not -path "*.git/*" -not -path "*/standard.dictionary" > $ZARGS_LOC/dotfiles

# next-august md and mdx files
find $HOME/ds/next/next-august/content -type f -iname "*.md*" -not -path "*/node_modules/*" > $ZARGS_LOC/mdx

# object manager
find $NC/src/nova-commons/src/components/ObjectManager -type f > $ZARGS_LOC/objectmgr

# nexpackage.json
find ~/nex -type f -name "package.json" -not -path "*/node_modules/*" -not -path "*/.next/*" -not -path "*/.contentlayer/*" > $ZARGS_LOC/nexpackagejson

# novapackage.json
find $NC -type f -iname "*package.json*" -not -path "*/node_modules/*" > $ZARGS_LOC/novapackagejson
cat << EOF >> $ZARGS_LOC/novapackagejson
${NC}/tools/create-nova-app/createNovaApp.js
EOF

# tsconfig
find $NC -type f -iname "*tsconfig.json*" -not -path "*/node_modules/*" > $ZARGS_LOC/tsconfig

# babel
find $NC -type f -iname "*babel.*config*" -not -path "*/node_modules/*" > $ZARGS_LOC/babel

echo "zargs updated"

